# Generated by Django 4.2.20 on 2025-04-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ETF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("krcode", models.CharField(max_length=30, unique=True)),
                ("asset_class", models.CharField(max_length=50)),
                (
                    "sub_strategy",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("inception_date", models.DateField(blank=True, null=True)),
                ("expense_ratio", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvestorSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("q1_1", models.CharField(max_length=100)),
                ("q1_2", models.CharField(max_length=100)),
                ("q1_3", models.CharField(max_length=100)),
                ("q2_1", models.CharField(max_length=100)),
                ("q2_2", models.CharField(max_length=100)),
                ("q2_3", models.CharField(max_length=100)),
                ("q2_4", models.CharField(max_length=100)),
                ("q3", models.CharField(max_length=100)),
                ("q4", models.CharField(max_length=100)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "profile_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ETFPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("close", models.FloatField()),
                ("aum", models.FloatField()),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RiskProfiling.etf",
                    ),
                ),
            ],
            options={
                "unique_together": {("etf", "date")},
            },
        ),
    ]
