# Generated by Django 4.2.20 on 2025-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investorsurvey",
            name="q4",
        ),
        migrations.AddField(
            model_name="investorsurvey",
            name="is_vulnerable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q1_1",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q1_2",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q1_3",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q2_1",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q2_2",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q2_3",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q2_4",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="investorsurvey",
            name="q3",
            field=models.FloatField(),
        ),
    ]
