# Generated by Django 4.2.20 on 2025-04-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0002_remove_investorsurvey_q4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETFDelta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("delta", models.FloatField()),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RiskProfiling.etf",
                    ),
                ),
            ],
            options={
                "unique_together": {("etf", "date")},
            },
        ),
    ]
