# Generated by Django 4.2.20 on 2025-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0003_etfdelta"),
    ]

    operations = [
        migrations.AddField(
            model_name="etfdelta",
            name="base_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
