# Generated by Django 4.2.20 on 2025-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0004_etfdelta_base_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etfdelta",
            name="base_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="etfdelta",
            name="date",
            field=models.DateField(),
        ),
    ]
