# Generated by Django 4.2.20 on 2025-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0005_alter_etfdelta_base_price_alter_etfdelta_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubStrategyRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("sub_strategy", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
            ],
            options={
                "ordering": ["year", "month", "rank"],
                "unique_together": {("year", "month", "sub_strategy")},
            },
        ),
        migrations.CreateModel(
            name="StrategyRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("sub_strategy", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
            ],
            options={
                "unique_together": {("year", "month", "sub_strategy")},
            },
        ),
    ]
