# Generated by Django 4.2.20 on 2025-04-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0006_substrategyranking_strategyrank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bond", "채권형"),
                            ("equity", "주식형"),
                            ("combined", "혼합형"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_date", models.DateField()),
                ("initial_invest", models.FloatField()),
                ("cash", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RiskProfiling.etf",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="RiskProfiling.portfolio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioNAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("nav", models.FloatField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RiskProfiling.portfolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "date")},
            },
        ),
    ]
