# Generated by Django 4.2.20 on 2025-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0007_portfolio_portfolioitem_portfolionav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
