# Generated by Django 4.2.20 on 2025-04-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RiskProfiling", "0009_alter_portfolio_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="base_date",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="cash",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="initial_invest",
        ),
        migrations.RemoveField(
            model_name="portfolioitem",
            name="portfolio",
        ),
        migrations.RemoveField(
            model_name="portfolioitem",
            name="weight",
        ),
        migrations.CreateModel(
            name="PortfolioVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="RiskProfiling.portfolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "base_date")},
            },
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="RiskProfiling.portfolioversion",
            ),
        ),
    ]
