# Generated by Django 4.2.20 on 2025-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "RiskProfiling",
            "0010_remove_portfolio_base_date_remove_portfolio_cash_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="investorsurvey",
            name="selected_strategy",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
